name: ClearLaggEnhanced
version: ${project.version}
main: com.clearlagenhanced.ClearLaggEnhanced
api-version: 1.20
folia-supported: true
authors: [djtmk]
description: A modern, customizable lag prevention plugin for Minecraft servers
website: https://github.com/BusyBee-Development/ClearLaggEnhanced
softdepend: [PlaceholderAPI]
libraries:
  - com.zaxxer:HikariCP:7.0.2
  - org.xerial:sqlite-jdbc:3.50.3.0
  - net.kyori:adventure-text-minimessage:4.24.0

commands:
  lagg:
    description: Main ClearLaggEnhanced command
    usage: /lagg <subcommand>
    aliases: [clearlagg, clearlag, cl, cle]

permissions:
  CLE.*:
    description: All ClearLaggEnhanced permissions
    children:
      CLE.help: true
      CLE.clear: true
      CLE.next: true
      CLE.tps: true
      CLE.ram: true
      CLE.chunkfinder: true
      CLE.admin: true
      CLE.reload: true
  CLE.help:
    description: Access to help command
    default: true
  CLE.clear:
    description: Access to clear command
    default: op
  CLE.next:
    description: Access to next command
    default: true
  CLE.tps:
    description: Access to tps command
    default: op
  CLE.ram:
    description: Access to ram command
    default: op
  CLE.chunkfinder:
    description: Access to chunkfinder command
    default: op
  CLE.admin:
    description: Access to admin GUI
    default: op
  CLE.reload:
    description: Access to reload command
    default: op
